# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('time_stamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.AddField(
            model_name='data',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_movie_app.Item'),
        ),
        migrations.AddField(
            model_name='data',
            name='rater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_movie_app.Rater'),
        ),
    ]
